baseURL = "https://hanamibienetre.fr/"
languageCode = "fr-FR"
title = "Hanami Bien-Ãªtre"
theme = "hanamibienetre"
paginate = 16
enableRobotsTXT = true

[params]
    author = "Marie Gosset"
    address = "4 Impasse LÃ©nine, 78800 Houilles, France"
    phone = "06 15 04 73 69"
    email = "marie@hanamibienetre.fr"
    mapURL = "https://www.google.com/maps/place/Hanami+Bien-%C3%AAtre/@48.919024,2.1982835,15z/data=!4m5!3m4!1s0x0:0xae746459d5aef600!8m2!3d48.919024!4d2.1982835"
    bookURL = "https://widget.treatwell.fr/salon/hanami-bien-etre/"
    banner = "Bonne et heureuse annÃ©e 2023 ðŸŒ¸ðŸŒ¸"
    social = [ "https://www.facebook.com/Hanamibienetre/", "https://www.instagram.com/hanami_bienetre/" ]

    [home]
    lastPostURL = "actualites"
    listDirURL = "nos-massages"